name = "inconigto"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true
routes = [
  { pattern = "inconigto.us.kg", custom_domain = true },
  { pattern = "ava.game.naver.com.inconigto.us.kg", custom_domain = true },
  { pattern = "graph.instagram.com.inconigto.us.kg", custom_domain = true },
  { pattern = "zaintest.vuclip.com.inconigto.us.kg", custom_domain = true },
  { pattern = "support.zoom.us.inconigto.us.kg", custom_domain = true },
  { pattern = "cache.netflix.com.inconigto.us.kg", custom_domain = true }
]
[vars]
